version: '3.9'

services:
  web:
    build: .
    command: /app/entrypoint.sh  
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - web
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:
