"""add is_active to Loan

Revision ID: a334edcbd58d
Revises: 1ca63e8d10d7
Create Date: 2025-05-05 13:30:38.563238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a334edcbd58d'
down_revision = '1ca63e8d10d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
